#!/usr/bin/env bash

## Configuration
################
# Saves the date when the last update was performed.
DATEFILE="${HOME}/.local/state/last_sys_update"
# Command to update all AUR packages.
AUR_UPDATE_CMD="malgware update"
# Whether to clear all pacman cache entries (yes) or just the ones for old
# packages.
CACHE_CLEAR_ALL="yes"
# If you're gaming on this system, it's recommended to use ProtonPlus to
# manage Proton versions.
PROTONPLUS_BIN='flatpak run com.vysp3r.ProtonPlus'

## Constants
############
CURR_S=`date "+%s"`
HOUR_S=$((60*60))
DAY_S=$((24*HOUR_S))
WEEK_S=$((7*DAY_S))

## Helpers
##########
# $1: id of the flatpak package to verify.
_installed_from_flatpak() {
   # If a flatpak is installed, `command -v` will return 2 lines:
   # - The first for flatpak itself, ended in "/flatpak".
   # - The second for the flatpak package.
   # No second line means the flatpak is not installed.
   # No lines are returned if flatpak is not installed either.
   if [ ! -z "$(command -v flatpak run $1 | grep -vE '/flatpak$')" ]; then
      return 0
   else
      return 1
   fi
}


# Notify the user if a week has passed since the last update.
notify_new_update() {
   # If it's our first time running the script, just record the current date.
   if [ ! -f $DATEFILE ]; then
      echo $((CURR_S - (CURR_S % DAY_S) - HOUR_S)) > $DATEFILE
      exit
   fi

   # Otherwise, check if it's been a week since the last run yet.
   LAST_S=`cat $DATEFILE`
   PASS_S=$((LAST_S + WEEK_S))
   # If not, leave.
   if [ $PASS_S -gt $CURR_S ]; then
      exit
   fi

   # Notify the user that it's time to update!
   notify-send "Updates!" "Remember to run \`forgwtful do\` soon!"
}

# Remove orphaned packages and unused dependencies.
remove_unused() {
   echo "Removing orphans and their unused dependencies..."
   sudo pacman -Qdtq | sudo pacman -Rs -

   echo "Cleaning pacman cache up..."
   # Failed downloads may leave partial artifacts behind.
   sudo rm -rf /var/cache/pacman/pkg/download-*
   # `-Sc` clear all cache entries for unused packages (old versions, uninstalled)
   # `-Scc` just deletes everything.
   [ "$CACHE_CLEAR_ALL" = "unused" ] && sudo pacman -Sc || sudo pacman -Scc
}

# Run updates.
do_new_update() {
   echo "Updating Arch repository mirror list..."
   sudo reflector @/etc/xdg/reflector/reflector.conf
   echo ""

   echo "=========================="
   echo "Running system updates..."
   sudo pacman -Syu
   echo ""

   echo "=========================="
   echo "Updating AUR packages..."
   $AUR_UPDATE_CMD
   echo ""

   if [ ! -z "$(command -v flatpak)" ]; then
      echo "=========================="
      echo "Running flatpak updates..."
      flatpak update
      echo ""
   fi

   if _installed_from_flatpak ${PROTONPLUS_BIN##* }; then
      echo "=========================="
      echo "Updating all Proton versions..."
      $PROTONPLUS_BIN update all
   fi

   echo $((CURR_S - (CURR_S % DAY_S) - HOUR_S)) > $DATEFILE
}

# Consult when the last update was ran from the terminal.
when_last_update() {
   LAST=`cat $DATEFILE`
   NEXT=$((LAST + WEEK_S))
   NOW=`date '+%s'`
   echo "Last update ran on:"
   echo "   $(date '+%D' --date=@$LAST)"
   if [ $NOW -lt $NEXT ]; then
      echo "Update as early as:"
      echo "   $(date '+%D' --date=@$NEXT)"
   else
      echo "Consider updating soon!"
   fi
}

# $1: specificies the script's operation mode.
#     - `check` notifies the user if it's been longer than a week since the last
#     `do` run.
#     - `clean` removes orphans and their unwanted dependencies.
#     - `do` updates all system and flatpak packages.
#     - `when` shows whether it's been longer than a week since the last `do`
#     run in the terminal.
case $1 in
   "check") notify_new_update ;;
   "clean") remove_unused ;;
   "do") do_new_update ;;
   "when") when_last_update ;;
   *)
   echo "Usage:"
   echo "   forgwtful check   Notifies the user if it's been longer than a week since the last \`do\` run."
   echo "   forgwtful clean   Removes orphaned packages and their unwanted dependencies."
   echo "   forgwtful do      Runs an update of system and flatpak packages, records the date."
   echo "   forgwtful when    Consults if it's been longer than a week since the last \`do\` run from CLI."
   ;;
esac
